import { parse_grammar, type grammar } from "./grammar.ts";
import { analyze, type analysis } from "./analyze.ts";
// The *.flat.gram files are generated by scripts/flatten.ts (run before the
// bundle): each is a language manifest with all %include / %import directives
// already resolved, so no file resolver is needed at runtime. esbuild's .gram
// text loader inlines them as strings.
import en_text from "../languages/english/en.flat.gram";
import sv_text from "../languages/swedish/sv.flat.gram";
import ru_text from "../languages/russian/ru.flat.gram";

const grammars: Record<string, grammar> = {
    en: parse_grammar(en_text),
    sv: parse_grammar(sv_text),
    ru: parse_grammar(ru_text),
};

// check(sentence) keeps the original single-argument signature (defaults to
// English); pass a language code as the second argument to switch.
export function check(sentence: string, lang: string = "en"): analysis {
    return analyze(grammars[lang] ?? grammars.en, sentence);
}
