import { parse_grammar } from "./grammar.ts";
import { analyze, type analysis } from "./analyze.ts";
// en.flat.gram is generated by scripts/flatten.ts (run before the bundle): it
// is en.gram with all %include / %import directives already resolved, so no
// file resolver is needed at runtime.
import gram_text from "../languages/english/en.flat.gram";

const grammar = parse_grammar(gram_text);

export function check(sentence: string): analysis {
    return analyze(grammar, sentence);
}
